# nextgen/data.py

from collections import namedtuple
import re

SKIP_PATTERNS = (
    "trump",
    "neutral",
    "grifter",
    "traffic",
    "trafficing",
    "tyrrany",
    "sex",
    "(NY POST)",
    "scandal",
    "ACB",
    "locked up",
    "Lagos",
    "Judge Barret",
    "Barret",
    "(vote red)",
    "red",
    "Streisand",
    "censoring",
    "must-read thread",
    "civil war",
    "realDonaldTrump",
    "illegal",
    "coordinated intervention",
    "intervention",
    "email",
    "seanhannity",
    "awards",
    "award",
    "blackmail",
    "male",
    "best",
    "malfeasance",
    "monopolies",
    "pretty",
    "poop",
    "shit",
    "penis",
    "vagina",
    "smirk",
    "(pretty girl)",
    "chronic",
    "monopoly",
    "maga",
    "graft",
    "stfu",
    "dynasty",
    "scummy",
    "nigerian",
    "liar",
    "scandal",
    "veritas",
    "lied",
    "maga",
    "hunter",
    "ukraine",
    "scandal",
    "pcas",
    "nypost",
    "burisma",
    "censor",
    "music",
    "ukrainian",
    "corrupt",
    "fbi",
    "(big tech)",
    "league",
    "(People's Choice Awards)",
)

SKIP_RE = re.compile("|".join(SKIP_PATTERNS), re.IGNORECASE)

TRUMP_PATTERNS = (
    "trump2020",
    "maga2020",
)

TRUMP_RE = re.compile("|".join(TRUMP_PATTERNS), re.IGNORECASE)

PROMOTION_TWEETS = (
    "There's just over 1 week left to vote! Make your plan today: http://nxtgn.us/pcp",
    "Millions of young people have already voted! Vote early: http://nxtgn.us/pcp",
    "If you haven't already, make your plan to vote by November 3! http://nxtgn.us/pcp",
    "We have the power to decide this election! Vote by November 3rd! http://nxtgn.us/pcp",
    "This is one of the most consequential elections of our lifetime. Make a plan to vote today: http://nxtgn.us/pcp",
    "Have you made your plan to vote yet? If not, do so here: http://nxtgn.us/pcp",
    "Make a plan to vote today: http://nxtgn.us/pcp! Then, encourage your friends and family to vote too!",
    "We all need to vote by November 3rd! Use our link to make a plan! http://nxtgn.us/pcp",
    "What's your plan to vote by next Tuesday 11/3?  http://nxtgn.us/pcp",
    "We are hitting 2008 youthvote numbers. But, we can do better. Make a plan to vote TODAY. http://nxtgn.us/pcp",
    "What's your plan to save democracy by Novemeber 3rd. http://nxtgn.us/pcp",
    "First step is finding your polling location. The second is making a plan to get there. Do you need a ride? can you bring 3 friends? Let us know! http://nxtgn.us/pcp",
    "This election is ours. We are the deciding vote. Vote by November 3rd! http://nxtgn.us/pcp",
    "How are you voting? Early voting 🙌🏾 🙌🏾 or Voting on election day 👏🏼👏🏼  Just PLAN IT OUT! http://nxtgn.us/pcp",
    "November 3rd is the last day to vote in this election. What's your plan to vote by election day? http://nxtgn.us/pcp",
    "It going to take the us to change the futire of this democracy. Make a plan to vote for the future. http://nxtgn.us/pcp",
    "November 3rd will be here before you know it. Make a plan to vote TODAY. http://nxtgn.us/pcp",
    "VOTE VOTE VOTE VOTE VOTE VOTE VOTE VOTE VOTE VOTE. Just do it! http://nxtgn.us/pcp",
    "🗣 MAKE A PLAN TO VOTE! http://nxtgn.us/pcp",
    "Have you taken your ballot back to your board of elections? Track your ballot http://nxtgn.us/pcp",
    "Use the link to make a plan to vote. http://nxtgn.us/pcp",
    "This is the most exciting election of our lives. Millions of young voters have voted. Join the club. http://nxtgn.us/pcp",
    "Your vote is the most powerful thing you have this election season. Make a plan to flex your constitutional right. http://nxtgn.us/pcp",
    "Climate Change is on the ballot! http://nxtgn.us/pcp",
    "Healthcare is on the ballot! http://nxtgn.us/pcp",
    "Racial Justice is on the ballot! http://nxtgn.us/pcp",
    "Flipping the senate is on the ballot! http://nxtgn.us/pcp",
    "Widening our majority in the house is on the ballot! http://nxtgn.us/pcp",
    "This country is ours. Lets vote like it! http://nxtgn.us/pcp",
    "Vote as soon as possible. http://nxtgn.us/pcp",
    "Vote like your life depends on it. http://nxtgn.us/pcp",
    "Simple... Make a plan to vote for change. http://nxtgn.us/pcp",
    #    "Nudes here ---> http://nxtgn.us/pcp",
    "Flagging this super important voter information ---> http://nxtgn.us/pcp",
    "Making a plan to vote takes no time at all. Do so right now: http://nxtgn.us/pcp",
    "This is going to be a revolutionary election. Be a part of history by making your plan to vote early today: http://nxtgn.us/pcp",
    "The future of democracy is at stake. Make a plan to vote to save our futures: http://nxtgn.us/pcp",
    "We have to vote for those who can’t. Make a plan here: http://nxtgn.us/pcp",
    "Voting early is in style! Try it out by making a plan: http://nxtgn.us/pcp",
    "If you haven’t voted yet, do so ASAP. Click here: http://nxtgn.us/pcp",
    "Democrats across the nation fought to expand voter access through early voting. Take advantage of this secure option by making a plan today: http://nxtgn.us/pcp",
    "If you’ve already voted, send this to 3 other people so they can make their early voting plan: http://nxtgn.us/pcp",
    "Planning your vote makes casting your ballot that much easier. Make a plan now: http://nxtgn.us/pcp",
    "Use your voice to create change by planning to vote early. Click here: http://nxtgn.us/pcp",
    "Early voting has started across the country, make your plan today: http://nxtgn.us/pcp",
    "Make a plan to join the millions of people who already participated in this record-breaking year for early voting: http://nxtgn.us/pcp",
    "Vote early and help end the nightmare: http://nxtgn.us/pcp",
    "Get out and vote as early as possible! http://nxtgn.us/pcp",
    "Find out if you can vote early in your state by clicking here: http://nxtgn.us/pcp",
    "Vote down-ballot, vote for change, and vote early. http://nxtgn.us/pcp",
    "One way to stop the spread is by voting early to avoid the Election Day lines. Make a plan: http://nxtgn.us/pcp",
    "Today is a great day to save democracy. Make a plan to vote by November 3rd. http://nxtgn.us/pcp",
    "Dump the Trump administration by voting by Election Day! http://nxtgn.us/pcp",
    "Your vote matters! Make a plan to cast your ballot here: http://nxtgn.us/pcp",
    "Use your powerful voting power to make a change. Plan your vote out here: http://nxtgn.us/pcp",
    "Head to the polls prepared on Election Day by making a plan now: http://nxtgn.us/pcp",
    "Make sure you have a complete voting plan for E-Day to save time at the polls by clicking here: http://nxtgn.us/pcp",
    "Do you know where and what time you’ll be voting this year? Get the details sorted out today: http://nxtgn.us/pcp",
    "Don't wait until November 3rd to vote. Make a plan to vote early here: http://nxtgn.us/pcp",
)

State = namedtuple("State", ("name", "code"))
